name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Aciona o workflow quando há push para a branch main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: meu-servico  # Nome do serviço no Cloud Run
  REGION: us-central1        # Região do Cloud Run

jobs:
  setup-build-deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'  # Necessário para autenticação com o Google Cloud

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Configura o gcloud CLI
    - name: Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # Chave da service account
        
    - name: Enable required services
      run: |-
        gcloud services enable \
          cloudbuild.googleapis.com \
          run.googleapis.com \
          artifactregistry.googleapis.com \
          --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Constrói e envia a imagem para o Google Container Registry
    - name: Build and Push Container
      run: |-
        gcloud builds submit \
          --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --project $PROJECT_ID

    # Implanta no Cloud Run
    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --project $PROJECT_ID
